DROP TABLE IF EXISTS ordered_items
CASCADE;

CREATE TABLE ordered_items
(
  id SERIAL PRIMARY KEY NOT NULL,
  food_id INTEGER REFERENCES foods(id) ON DELETE CASCADE,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  qty INTEGER
);
